name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22 # Укажи свой порт, если он нестандартный
          script: |
            cd /var/www/wibe-messenger
            # Убедись, что права на запуск есть
            chmod +x deploy.sh
            # Запуск скрипта деплоя
            ./deploy.sh